// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnzgzxpguhbycriftzxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxuemd6eHBndWhieWNyaWZ0enhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTA1NTUsImV4cCI6MjA2ODc2NjU1NX0.KuH947s_BV9KyD5AKlQs0UlotTEvYodxJybdEdykFss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});